Enable compatibility for Ubuntu22.04 LTS and RHEL8
awslabs/aws-ec2rescue-linux pull request #85
Opened 2022-09-01 18:04 UTC by gregbdunn

Currently, ec2rl does not support RHEL8 or Ubuntu 22.04

For Ubuntu, Python3.10 breaks the functionality for older versions of requests, yaml, and jmespath. I have moved the old versions to the python2 specific vended directory, and included updated versions of these libraries in the python3 specific vended directory.

For RHEL8, Red Hat changed the format of /etc/os-release. I have updated prediag.py to a regex that will catch older versions as well as the new version.

I have tested that ec2rl runs on RHEL7, RHEL8, ALAMI2, Ubuntu18.04, Ubuntu 22.04, SLES12, SLES15 with these changes.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-09-04 19:32 UTC, Drudenhaus requested changes
Could you add a test for the new RHEL string (to serve as a regression test)?

2022-09-20 20:43 UTC, gregbdunn commented
Done!

[root@ip-172-16-1-112 aws-ec2rescue-linux]# python3 -m unittest test/test_prediag.py
...................................................................
----------------------------------------------------------------------
Ran 67 tests in 0.109s

2022-09-21 02:16 UTC, Drudenhaus commented
LGTM

2022-09-21 02:17 UTC, Drudenhaus approved these changes

2022-09-21 02:18 UTC, merged