Add sosreport and supportconfig modules
awslabs/aws-ec2rescue-linux pull request #91
Opened 2023-03-01 20:02 UTC by gregbdunn

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Adds modules that gathers sosreport and supportconfig outputs

2023-07-28 06:28 UTC, Drudenhaus requested changes
supportconfig module has multiple sosreport references.

2023-07-28 06:28 UTC, Drudenhaus commented on mod.d/supportconfig.yaml
> +  Gather an sosreport
s/sosreport/supportconfig

2023-07-28 06:28 UTC, Drudenhaus commented on mod.d/supportconfig.yaml
> +  echo "I have attempted to gather unsanitized sosreport output to $EC2RL_GATHEREDDIR/sosreport"
s/sosreport/supportconfig

2023-07-28 06:28 UTC, Drudenhaus commented on mod.d/supportconfig.yaml
> +  echo "I will gather the output of an sosreport"
s/sosreport/supportconfig

2023-08-10 16:37 UTC, gregbdunn commented on mod.d/supportconfig.yaml
> +  echo "I will gather the output of an sosreport"
Fixed these ups

2023-08-28 19:56 UTC, Drudenhaus approved these changes

2023-08-28 20:05 UTC, gregbdunn commented
Drudenhaus is dealing with some permissions related issues so he can't issue official approval, but considering this approved for all intents and purposes.

2023-08-28 20:05 UTC, merged